// SPDX-FileCopyrightText: 2020 Pier Luigi Fiorini <pierluigi.fiorini@gmail.com>
//
// SPDX-License-Identifier: GPL-3.0-or-later

#ifndef LOGGING_P_H
#define LOGGING_P_H

#include <QLoggingCategory>

Q_DECLARE_LOGGING_CATEGORY(lcPortal)
Q_DECLARE_LOGGING_CATEGORY(lcAccess)
Q_DECLARE_LOGGING_CATEGORY(lcAccount)
Q_DECLARE_LOGGING_CATEGORY(lcAppChooser)
Q_DECLARE_LOGGING_CATEGORY(lcBackground)
Q_DECLARE_LOGGING_CATEGORY(lcEmail)
Q_DECLARE_LOGGING_CATEGORY(lcFileChooser)
Q_DECLARE_LOGGING_CATEGORY(lcInhibit)
Q_DECLARE_LOGGING_CATEGORY(lcNotification)
Q_DECLARE_LOGGING_CATEGORY(lcPrint)
Q_DECLARE_LOGGING_CATEGORY(lcRequest)
Q_DECLARE_LOGGING_CATEGORY(lcScreenCast)
Q_DECLARE_LOGGING_CATEGORY(lcScreenshot)
Q_DECLARE_LOGGING_CATEGORY(lcSession)
Q_DECLARE_LOGGING_CATEGORY(lcSettings)
Q_DECLARE_LOGGING_CATEGORY(lcWallpaper)
Q_DECLARE_LOGGING_CATEGORY(lcWaylandIntegration)

#endif // LOGGING_P_H
